language: python
python:
  - "3.2"
  - "3.3"
branches:
  only:
    - master
    - develop

# command to run tests
script: nosetests

notifications:
  irc:
    channels:
      - "chat.freenode.net#bogo"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository}/%{branch}#%{commit} (%{author})"
      - "%{message} %{build_url}"
